name: Auto Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'notes/**'
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: notes
            path: notes
            image: hriteshsaha4/zapnotes-frontend
          - name: server
            path: server
            image: hriteshsaha4/zapnotes-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect changes in ${{ matrix.name }}
        id: changes
        run: |
          echo "Checking for changes in ${{ matrix.path }}"
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^${{ matrix.path }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push ${{ matrix.image }}:dev
        if: steps.changes.outputs.changed == 'true'
        run: |
          docker build -t ${{ matrix.image }}:dev ${{ matrix.path }}
          docker push ${{ matrix.image }}:dev
